server:
  port: 8080
  servlet:
    context-path: /api
 
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sound_verse"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
  mail:
    host: smtp.gmail.com      
    port: 587                
    username: kienvanvo7777@gmail.com
    password: hrjf hkdi giwa svrs
    properties:
      mail:
        smtp:
          auth: true        
          starttls:
            enable: true    
            required: true      
          connectiontimeout: 5000  
          timeout: 5000            
          writetimeout: 5000        
    protocol: smtp            
    default-encoding: UTF-8  
jwt:
  signerKey: "85c2f38f-973d-451e-af68-e73e2ef2bee5"
 
aws:
  accessKeyId: "AKIAW6LI6XSY4L6MVBUH"
  secretAccessKey: "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"
  region: "us-east-1"
  bucketName: "sound-verse"